require: rubocop-rails
AllCops:
  TargetRubyVersion: 2.6.3
  Exclude:
    - 'config/routes.rb'
    - 'tmp/**/*'
    - 'db/schema.rb'

Style/FrozenStringLiteralComment:
  Enabled: true
  
Style/ClassAndModuleChildren:
  Enabled: false
  # EnforcedStyle: compact

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/MutableConstant:
  Enabled: false

Metrics/LineLength:
  Max: 140

Metrics/ClassLength:
  Max: 140

Metrics/MethodLength:
  Max: 140

Metrics/ModuleLength:
  Max: 140

Metrics/BlockLength:
  Max: 140

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# Metrics/PerceivedComplexity:
#   Enabled: false

Style/GlobalVars:
  Enabled: false

# Style/GuardClause:
#   Enabled: false

Rails/FindBy:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/CreateTableWithTimestamps:
  Enabled: false