redis:
  host: 127.0.0.1
  password: rails_best
  namespace: rails_best
  port: 6379
  queue: 1
  cache: 2
  object_db: 3
  sidekiq_db: 4
  expires_in: 3600
mailer:
  from: 651019063@qq.com
  address: smtp.mxhichina.com
  port: 465
  domain: qq.com
  user_name: 651019063@qq.com
  password: xxxxxx
  authentication: plain
  ssl: true
  exception_recipients:
    - 651019063@qq.com