redis:
  host: 127.0.0.1
  password: small_shop
  namespace: small_shop
  port: 6379
  queue: 1
  cache: 2
  object_db: 3
  sidekiq_db: 4
  expires_in: 3600
mailer:
  from: gyf006@17cc.cn
  address: smtp.mxhichina.com
  port: 465
  domain: 17cc.cn
  user_name: gyf006@17cc.cn
  password: Gu1212036
  authentication: plain
  ssl: true
  exception_recipients:
    - 651019063@qq.com